### ISSUE TITLE
The program is power-consuming and missing keys

### ISSUE THREAD

**Issue by Glaciohound** [millerjs/modelm#12]
Love it! The sound effect is good and I feel like really being using a mechanical keyboard.

However, the program consumes a lot of power, which is unbearable for my poor Macbook air.
Also, the program could not detect some special keys like "Shift" and "Ctrl" "F1" "F2", etc.

If these problems could be solved, this program would be perfect!

**Comment by millerjs** [comment]
Thanks for the feedback, @hericopter ! I'm sorry to hear about the power consumption, I'll see what I can do regarding that.

The special keys not registering might be a "feature", as I hit control a lot and didn't want to hear it all the time. However, I've addressed this in https://github.com/millerjs/modelm/pull/7 but as https://github.com/millerjs/modelm/issues/8 points out, there's no binary built for the latest version. Since there's interest, I'll look to release again soon

**Comment by Glaciohound** [comment]
Thanks!
That would be great
